ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),

    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),

    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),

    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),

    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),

    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),

]

autos/urls.py
from django.urls import path
from . import views

app_name = 'autos'
urlpatterns = [

    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),

    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

django_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    path('ads/', include('ads.urls')),
    path('autos/', include('autos.urls')),
]

autos/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


class Make(models.Model):
    name = models.CharField(
            max_length=200,
            help_text='Enter a make (e.g. Dodge)',
            validators=[MinLengthValidator(2, "Make must be greater than 1 character")]
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Auto(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Shows up in the admin list
    def __str__(self):
        return self.nickname

autos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from autos.models import Auto, Make

# Create your views here.
#-----------------------------------------------------------------------------

class MainView(LoginRequiredMixin, View):
    def get(self, request):
        mc = Make.objects.all().count()
        al = Auto.objects.all()

        ctx = {'make_count': mc, 'auto_list': al}
        return render(request, 'autos/auto_list.html', ctx)


class MakeView(LoginRequiredMixin, View):
    def get(self, request):
        ml = Make.objects.all()
        ctx = {'make_list': ml}
        return render(request, 'autos/make_list.html', ctx)

#------------------------------------------------------------------------------

class MakeCreate(LoginRequiredMixin, CreateView):
    model = Make
    fields = ['name']
    success_url = reverse_lazy('autos:all')

    # Valid Form
    def form_valid(self, form):
        posts = Make.objects.filter(owner__username=self.request.user)
        post_num = posts.count()

        # User has 3 or less makes
        if post_num < 3:
            # Add owner to the model before saving
            make = form.save(commit=False)
            make.owner = self.request.user
            make.save()
            return redirect(self.success_url)
        # User has more than 3 makes
        else:
            return render(self.request, 'autos/make_form.html', {'form': form, 'error': 'Limit exceeded'})


class MakeUpdate(LoginRequiredMixin, UpdateView):
    model = Make
    #Shows all fields of Make table
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class MakeDelete(LoginRequiredMixin, DeleteView):
    model = Make
    #Shows all fields of Make table
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

#------------------------------------------------------------------------------

class AutoCreate(LoginRequiredMixin, CreateView):
    model = Auto
    #fields = '__all__'
    fields = ['nickname', 'mileage', 'comments', 'make']
    success_url = reverse_lazy('autos:all')

    # Valid Form
    def form_valid(self, form):
        posts = Auto.objects.filter(owner__username=self.request.user)
        post_num = posts.count()

        # User has 3 or less autos
        if post_num < 3:
            # Add owner to the model before saving
            auto = form.save(commit=False)
            auto.owner = self.request.user
            auto.save()
            return redirect(self.success_url)
        # User has more than 3 makes
        else:
            return render(self.request, 'autos/auto_form.html', {'form': form, 'error': 'Limit exceeded'})

class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

autos/templates/autos/auto_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <div class="container text-center">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Delete Auto</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        <h4>Are you sure you want to delete the auto: {{ auto }}?</h4>
        <br>
        <form action="" method="POST">
            {% csrf_token %}
            <input class="btn btn-success" type="submit" value="Yes, delete.">
            <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'autos:all' %}' ; return false;">
                <i class="fas fa-times"></i> Cancel
            </button>
        </form>
    </div>
{% endblock %}

autos/templates/autos/auto_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Autos Form</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        <br>
        {% if error %}
            <div class="alert alert-danger" role="alert">
                <p>
                    {{ error }}! You have reached the autos limit (3). If you still
                    want to make some probes, delete one of your three autos or you can
                    just update them (it's the same as creating a new one).
                </p>
                <p>Cheers!<br>Alejandro Z. Z.</p>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Submit</button>
            <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
                <i class="fas fa-times"></i> Cancel
            </button>
        </form>
    </div>
{% endblock %}

autos/templates/autos/auto_list.html
{% extends "base_menu.html" %}
{% block content %}
    <div class="container text-center">
        <br>
        <h1 style="color: gray;"><b>Autos List</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        {% if auto_list %}
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Nickname</th>
                        <th scope="col">Make</th>
                        <th scope="col">Comments</th>
                        <th scope="col">Mileage [mph]</th>
                    </tr>
                </thead>
                <tbody>
                    {% for auto in auto_list %}
                        <tr>
                            <td>
                                {{ auto.nickname }}
                                {% if auto.owner == user %}
                                    ( <a href="{% url 'autos:auto_update' auto.id %}"><i class="fas fa-pencil-alt"></i></a> |
                                    <a href="{% url 'autos:auto_delete' auto.id %}"><i class="fas fa-trash-alt"></i></a> )
                                {% endif %}
                            </td>
                            <td>{{ auto.make }}</td>
                            <td>{{ auto.comments }}</td>
                            <td>{{ auto.mileage }}</td>
                        </tr>
                    {% endfor %}
            </table>
        {% else %}
            <h4><i class="fas fa-info-circle"></i> There are no autos in the library.</h4>
        {% endif %}
        {% if make_count > 0 %}
            <a class="btn btn-secondary" href="{% url 'autos:auto_create' %}"><i class="fas fa-car"></i> Add an auto</a>
        {% else %}
            <h4><i class="fas fa-info-circle"></i> Please add a make before you add an auto.</h4>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'autos:make_list' %}">View makes ({{ make_count }})</a>
        <a class="btn btn-secondary" href="{% url 'autos:make_create' %}"><i class="fas fa-plus"></i> Add a make</a>
    </div>
{% endblock %}

autos/templates/autos/make_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <div class="container text-center">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Delete Make</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        <h4>Are you sure you want to delete the make: {{ make }}?</h4>
        <br>
        <form action="" method="POST">
            {% csrf_token %}
            <input class="btn btn-success" type="submit" value="Yes, delete.">
            <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'autos:all' %}' ; return false;">
                <i class="fas fa-times"></i> Cancel
            </button>
        </form>
    </div>
{% endblock %}

autos/templates/autos/make_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Make Form</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        <br>
        {% if error %}
            <div class="alert alert-danger" role="alert">
                <p>
                    {{ error }}! You have reached the makes limit (3). If you still
                    want to make some probes, delete one of your three makes or you can
                    just update them (it's the same as creating a new one).
                </p>
                <p>Cheers!<br>Alejandro Z. Z.</p>
            </div>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Submit</button>
            <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
                <i class="fas fa-times"></i> Cancel
            </button>
        </form>
    </div>
{% endblock %}

autos/templates/autos/make_list.html
{% extends "base_menu.html" %}
{% block content %}
    <div class="container">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Make List</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        {% if make_list %}
            <ul class="list-group">
                {% for make in make_list %}
                    <li class="list-group-item">
                        {{ make.name }}
                        {% if make.owner == user %}
                            ( <a href="{% url 'autos:make_update' make.id %}"><i class="fas fa-pencil-alt"></i></a> |
                            <a href="{% url 'autos:make_delete' make.id %}"><i class="fas fa-trash-alt"></i></a> )
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <br>
        {% else %}
            <h4><i class="fas fa-info-circle"></i> There are no makes in the library.</h4>
        {% endif %}
        <div class="text-center">
            <a class="btn btn-secondary" href="{% url 'autos:make_create' %}"><i class="fas fa-plus"></i> Add a make</a>
        <a class="btn btn-secondary" href="{% url 'autos:all' %}"><i class="fas fa-car"></i> Back to autos</a>
        </div>
    </div>
{% endblock %}