ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),

    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),

    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),

    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),

    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),

    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),

]

django_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('hello/', include('hello.urls')),
    path('ads/', include('ads.urls')),
    path('autos/', include('autos.urls')),
]

ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

class Ad(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #add comments to every ad
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='comments_owned')

    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')

    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_ads')

    # Shows up in the admin list
    def __str__(self):
        return self.title

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15 : return self.text
        return self.text[:11] + ' ...'

class Fav(models.Model) :
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('ad', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.ad.title[:10])

ads/forms.py
from django import forms
from ads.models import Ad
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        fields = ['title', 'text', 'picture', 'price']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

ads/views.py
from ads.models import Ad, Comment, Fav
from ads.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse_lazy, reverse
from ads.forms import CreateForm, CommentForm
from django.db.models import Q
from django.contrib import messages

class AdListView(OwnerListView):
    model = Ad
    # By convention:
    template_name = "ads/ad_list.html"
    def get(self, request) :

        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            query = Q(title__contains=strval)
            query.add(Q(text__contains=strval), Q.OR)

            ad_list = Ad.objects.filter(query).select_related().order_by('-updated_at')[:10]

        else:
            ad_list = Ad.objects.all().order_by('-updated_at')

        #Get all id ads with favorite mark
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_ads.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]

        ctx = {'ad_list' : ad_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)

class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"

    def get(self, request, pk) :
        x = Ad.objects.get(id=pk)
        comments = Comment.objects.filter(ad=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'ad' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)

class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        # Form is valid
        if form.is_valid():
            posts = Ad.objects.filter(owner__username=self.request.user)
            post_num = posts.count()

            # User have not exceeded number of ads or its me
            if post_num < 3 or str(self.request.user) == 'AlejandroZZ':
                # Add owner to the model before saving
                ad = form.save(commit=False)
                ad.owner = self.request.user
                ad.save()
                return redirect(self.success_url)

            # User EXCEEDED number of ads
            else:
                return render(request, self.template_name, {'form': form, 'error': 'Limit exceeded'})

        # Form is not VALID
        else:
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, pk):
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()

        return redirect(self.success_url)

class AdDeleteView(OwnerDeleteView):
    model = Ad

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        form = CommentForm(request.POST)

        # Form is valid
        if form.is_valid():
            posts = Comment.objects.filter(owner__username=self.request.user)
            post_num = posts.count()

            # User have not exceeded number of comments
            if post_num < 5:
                f = get_object_or_404(Ad, id=pk)
                comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
                comment.save()
                return redirect(reverse('ads:ad_detail', args=[pk]))

            # User EXCEEDED number of ads
            else:
                messages.add_message(request, messages.INFO, "Limit exceeded")
                return redirect(reverse('ads:ad_detail', args=[pk]))

        # Form is not VALID
        else:
            messages.add_message(request, messages.ERROR, "Invalid comment")
            return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


def stream_file(request, pk):
    pic = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response


# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Ad, id=pk)
        fav = Fav(user=request.user, ad=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Ad, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <div class="container text-center">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Delete Ad</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        <h4>Are you sure you want to delete the ad: {{ ad }}?</h4>
        <br>
        <form action="" method="POST">
            {% csrf_token %}
            <input class="btn btn-success" type="submit" value="Yes, delete.">
            <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'ads:all' %}' ; return false;">
                <i class="fas fa-times"></i> Cancel
            </button>
        </form>
    </div>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
    <style>
    .overlay{
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 10;
      display: none;
      background-color: rgba(0,0,0,0.5); /*dim the background*/
    }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        {% if ad.content_type %}
            <div id="overlay" class="overlay" style="text-align: center;"
               onclick="document.getElementById('overlay').style.display = 'none';" >
                <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
            </div>
        {% endif %}
        <span style="float: right;">
            ({{ ad.updated_at|naturaltime }})
            {% if ad.owner == user %}
                <a href="{% url 'ads:ad_update' ad.id %}"><i class="fas fa-pencil-alt"></i></a>
                <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
            {% endif %}
        </span>
        <h1>{{ ad.title }}</h1>
        {% if ad.content_type %}
            <img style="float:right; max-width:50%; border-radius: 1rem; margin-left: 20px;" src="{% url 'ads:ad_picture' ad.id %}"
                onclick="document.getElementById('overlay').style.display = 'block';">
        {% endif %}
        <p>
            <b>Price: </b>${{ ad.price }} USD
        </p>
        <p style="text-align: justify;">
            <b>Description</b><br>
            {{ ad.text }}
        </p>
        {% if user.is_authenticated %}
            <br clear="all"/>
            <p>
                {% load crispy_forms_tags %}
                <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
                    {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type="submit" class="btn btn-outline-primary" value="Submit">
                    <input type="submit" class="btn btn-outline-secondary" value="All Ads" onclick="window.location.href='{% url 'ads:all' %}';return false;">
                </form>
            </p>
        {% endif %}
        <p></p>
        <p>
            <b>Comments</b>
        </p>
        {% if messages %}
            {% for message in messages %}
            <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/messages/#creating-custom-message-levels -->
                {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    <div class="alert alert-danger" role="alert">
                        <p>
                            {{ message }}! You can only make a total of 5 comments, including those made in other ads.
                        </p>
                        <p>Cheers!<br>Alejandro Z. Z.</p>
                    </div>
                {% else %}
                    <p style="color: red;"><b>
                        <i class="fas fa-exclamation-triangle"></i> {{ message }}. The comment must be at least 3 characters long.
                    </b></p>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% for comment in comments %}
            <div class="card border-secondary mb-3">
                <div class="card-body text-secondary">
                    <blockquote class="blockquote mb-0">
                        <p>
                            {{ comment.text }}
                            {% if user == comment.owner %}
                                ( <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a> )
                            {% endif %}
                        </p>
                    </blockquote>
                    (<i>{{ comment.updated_at|naturaltime }}</i>)
                </div>
            </div>
        {% endfor %}
        <p>
            {% url 'ads' as ads %}
            <br><br><br><br>
            <br>The request.get_full_path return this: {{ request.get_full_path }}
            <br>The ads variable is: {{ ads }}
        </p>
    </div>
{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <br>
        <h1 style="text-align: center; color: gray;"><b>Ads Form</b></h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        {% if error %}
            <br>
            <div class="alert alert-danger" role="alert">
                <p>
                    {{ error }}! You have reached the ads limit (3). If you still
                    want to make some probes, delete one of your three ads or you can
                    just update them (it's the same as creating a new one).
                </p>
                <p>Cheers!<br>Alejandro Z. Z.</p>
            </div>
        {% endif %}
        <p>
          <form action="" method="post" id="upload_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success"><i class="fas fa-check"></i> Submit</button>
            <button type="submit" class="btn btn-secondary" onclick="window.location='{% url 'ads:all' %}' ; return false;" value="Cancel">
                <i class="fas fa-times"></i> Cancel
            </button>
          </form>
        </p>
    </div>
    <!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
    <script>
    $("#upload_form").submit(function() {
      console.log('Checking file size');
      if (window.File && window.FileReader && window.FileList && window.Blob) {
          var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
          if (file && file.size > {{ form.max_upload_limit }} ) {
              alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
          return false;
        }
      }
    });
    </script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% load static %}
{% block head %}
    <style>
        .card{
            background-color: #343a40;
        }
        .text-muted {
            color: #acacac !important;
        }
        .card-body #btn-more{
            position: absolute;
            bottom: 30px;
            right: 30px;
        }
        .card-body a span{
            position: absolute;
            right: 50px;
            top: 18px;
        }
        .card-title h5{
            margin-bottom: 0px;
            color: white;
        }
        .card-body p{
            color: white;
        }
        #search{
            float: right;
        }
        #search .form-control{
            display: unset;
            width: auto;
        }
        #search .btn{
            vertical-align: baseline;
        }
        @media (max-width: 574px){
            .card-body a,
            .card-body #btn-more{
                position: unset;
            }
            .card-body #edit:after{
                content: "\00a0 \00a0";
            }
        }
        @media (max-width: 992px){
            #search{
                float: none;
            }
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <h1 style="text-align: center; color: gray;">
            <b>Ads</b>
            <button type="button" style="float: right; margin-top: 10px;"
                    class="btn btn-secondary rounded-pill" onclick="window.location='{% url 'ads:ad_create'%}';">
              <i class="fas fa-plus"></i> Create Ad
            </button>
        </h1>
        <hr style="border-top: 4px solid rgba(0, 0, 0, 0.5);">
        <div id="search">
            <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
            <form>
                <input type="text" placeholder="Search.." name="search" class="form-control"
                    {% if search %} value="{{ search }}" {% endif %}
                >
                <button type="submit" class="btn btn-dark"><i class="fas fa-search"></i></button>
                <a href="{% url 'ads:all' %}" class="btn btn-link"><i class="fas fa-undo"></i></a>
            </form>
        </div>
        <p>
            {% if ad_list %}
                {% for ad in ad_list %}
                    <div class="card mb-3" style="max-width: 540px;">
                      <div class="row no-gutters">
                          <div class="card-body">
                                <div class="card-title">
                                    <h5>
                                        {{ ad.title }}
                                        {% if ad.owner == user %}
                                            ( <a href="{% url 'ads:ad_update' ad.id %}"><i class="fas fa-pencil-alt"></i></a> |
                                            <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fas fa-trash-alt"></i></a> )
                                        {% endif %}
                                    </h5>
                                    <span class="card-text"><small class="text-muted">posted by {{ ad.owner.username }}</small></span>
                                </div>
                            <!-- Favorite Stars-->
                            {% if user.is_authenticated %}
                                <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                                <a href="#" onclick=
                                    "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }} );return false;"
                                    {% if ad.id not in favorites %} style="display: none;" {% endif %}
                                    id="favorite_star_{{ad.id}}">
                                    <span class="fa-stack" style="vertical-align: middle;">
                                        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                        <i class="fa fa-star-o fa-stack-1x"></i>
                                    </span>
                                </a>
                                <!-- the second href -->
                                <a href="#" onclick=
                                     "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }} );return false;"
                                    {% if ad.id in favorites %} style="display: none;" {% endif %}
                                    id="unfavorite_star_{{ad.id}}">
                                    <span class="fa-stack" style="vertical-align: middle;">
                                        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                                        <!--<i class="fa fa-star-o fa-stack-1x"></i>-->
                                        <i class="far fa-star fa-stack-1x"></i>
                                    </span>
                                </a>
                            {% endif %}
                            <p class="card-text" style="text-align: justify;">{{ ad.text }}</p>
                            <p class="card-text"><small class="text-muted">Last updated: {{ ad.updated_at|naturaltime }}</small></p>
                            <a id="btn-more" class="btn btn-outline-light btn-sm" href="{% url 'ads:ad_detail'  ad.id %}" role="button">More details</a>
                          </div>
                      </div>
                    </div>
                    <br>
                {% endfor %}
            {% else %}
                <p>There are no ads in the database.</p>
            {% endif %}
        </p>
    </div>
{% endblock %}
{% block script %}
    <script>
        function favPost(url, thing_id) {
            console.log('Requesting JSON');
            $.post(url, {},  function(rowz){
                console.log(url, 'finished');
                $("#unfavorite_star_"+thing_id).toggle();
                $("#favorite_star_"+thing_id).toggle();
            }).fail(function(xhr) {
                alert('Url failed with '+xhr.status+' '+url);
            });
        }
    </script>
{% endblock %}

ads/templates/ads/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <div class="container">
        <h1>Delete Comment</h1>

        <p>Are you sure you want to delete</p>
        <p>{{ comment.text }}?</p>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit"  class="btn btn-primary" value="Yes, delete.">
            <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}